import streamlit as st
st.set_page_config(layout="wide")
st.title("New Gallery")
st.subheader("1.gallery项目规划", divider=True)
st.write("我在Streamlit Cloud部署过的早期的gallery类项目由于使用的是过时的模型，近期已删除相应仓库。后面部署的Gallery项目则收集了多类模型生成的内容，Hunyuan Video Gallery项目则展示了使用Hunyuan Video生成的图片和视频，由于均达到可用水平，后续不会删除。")
st.write("本项目用于收录新一代模型生成的内容，在每一类型合适的模型推出后部署相应板块，而更晚的模型由于到时候有合适的LLM用于编写复杂网页，相关内容将会改为在Github Pages发布。")
st.write("此前的Streamlit项目为了在合并多个内容后减少文件数量，删除了记录使用LLM辅助生成页面的提示词的文件，本项目开始改为在对应文件的注释标出。")
st.subheader("2.旧项目中的模型存在的问题", divider=True)
st.write("AI图片模型此前使用Cogview4，算是在适用分辨率范围较大的情况下在光照和细节找到比较合适的平衡点，但这两方面表现不算优秀且相当一部分提示词表现较差。")
st.write("AI视频模型此前使用Wan2.1 1.3b，虽然生成较快但细节和运动表现有缺陷。")
st.write("AI音乐页面此前使用YuE，虽然可用但音质较差，不少片段无声乐。")
st.write("LLM查询页面此前主要使用Deepseek R1，基本符合需求，但由于查询流程简单以及只放到gallery时不方便在对话软件查找，已停止更新。")
st.write("LLM散文集页面此前使用Deepseek R1，虽然在写作上取得一定突破但逻辑仍然存在问题，长文写作基本不可用。")
st.write("p5js页面因p5js提供在线部署而创建，本地页面使用iframe存在问题。此前主要使用Deepseek R1，不少程序无法完成或需要降低要求。")
st.subheader("3.本项目中模型的优势", divider=True)
st.write("（由于在同一类型中可能引入不同侧重点的多个模型，子页面改为以模型名称命名）")
st.write("Wan2.1 14b虽然只能生成720p分辨率视频，但细节、光照和运动效果上都有一定优势。")
st.write("Pixelwave是Flux.1 dev的微调模型，解决了大部分材质和光照问题，并且能稳定生成1080p图片。")
st.write("与Wan2.1 14b不同，Fast Hunyuan是对Hunyuan Video的步骤蒸馏，大幅提升速度的同时画质损失较小，作为速度方向的视频模型添加到本项目。")